esphome:
  name: !secret "hostname"
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: !secret "wifi_ssid"
  password: !secret "wifi_pwd"

ota:
  password: !secret "ota_pwd"

web_server:
  port: 80

logger:

esp32_ble_tracker:

api:
  password: !secret "api_pwd"

mqtt:
  broker: !secret "mqtt_server"
  username: !secret "mqtt_user"
  password: !secret "mqtt_pwd"

sensor:
  - platform: xiaomi_miscale
    mac_address: !secret "scale_mac"
    weight:
      name: "Weight"
    impedance:
      name: "Impedance"