esphome:
  name: !secret "hostname"
  platform: ESP32
  board: esp32cam

wifi:
  ssid: !secret "wifi_ssid"
  password: !secret "wifi_pwd"

ota:
  password: !secret "ota_pwd"

web_server:
  port: 80

logger:

api:
  password: !secret "api_password"

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: Test Camera
  resolution: 1600x1200
  jpeg_quality: 10

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

light:
  - platform: binary
    output: gpio_4
    name: "ESP32Cam light"