esphome:
  name: !secret "hostname"
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret "wifi_ssid"
  password: !secret "wifi_pwd"

ota:
  password: !secret "ota_pwd"

web_server:
  port: 80

logger:

api:
  password: !secret "api_pwd"

mqtt:
  broker: !secret "mqtt_server"
  username: !secret "mqtt_user"
  password: !secret "mqtt_pwd"

i2c:
  - sda: GPIO4
    scl: GPIO5

sensor:
  #Temperatur und Luftfeuchtigkeit
  - platform: sht3xd
    address: 0x44
    
    temperature:
      name: "Temperatur"
      id: "temperature"
    humidity:
      name: "Luftfeuchtigkeit"
      id: "humidity"
    update_interval: 10s
    
  # MQ2 Smoke Gas Sensor
  - platform: adc
    pin: A0
    name: "Gassensor"
    update_interval: 10s
    filters:
     lambda: |- 
       return (x * 1024/5);
    unit_of_measurement: "ppm"  
    icon: "mdi:percent" 