esphome:
  name: bme280
  platform: ESP8266
  board: d1_mini
logger:
i2c:
  sda: D2
  scl: D1
sensor:
  - platform: bme280
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    address: 0x76
    update_interval: 10s